#!/bin/bash

if [ "$1" == "l" ] ; then
    cd ../../
    icmbuild
    exit $?
fi

if [ $# -eq 0 ] ; then
    echo "filename (w/o .cc) to compile needed"
else
    g++ --std=c++2a -Wall $1.cc  -L../../tmp -ldatetime -lbobcat -s
    if [ $? -eq 0 ] ; then
        tput clear
        a.out
    fi
fi
