#!/bin/bash

if [ "$1" == "l" ] ; then   # lima, not  one
    cd ../../
    icmbuild
    exit $?
fi

if [ $# -eq 0 ] ; then
    echo "filename (w/o .cc) to compile needed"
else
                                                    # -ldatetime
    g++ --std=c++2a -Wall -pthread $1.cc  -L../../tmp -lbobcat -s
    if [ $? -eq 0 ] ; then
        tput clear
        a.out
    fi
fi
