#!/bin/bash

tput clear

GPP="g++ --std=c++2a"

CMD="$GPP -o driver -Wall -I../ main.cc -L../tmp -lglob -lbobcat -s"
# CMD="$GPP -o driver -Wall -I../../tmp main.cc -L../../tmp/lib -lbobcat -s"
# CMD="$GPP -o driver -Wall -I../ main.cc -L../tmp -lglob -lbobcat -s"
# CMD="$GPP -o driver -Wall *.cc -lbobcat -s"

echo $CMD
$CMD || exit 1

echo "'driver' ready..."

