#!/bin/bash

tput clear

GPP="g++ `cat ../../c++std`"

CMD="$GPP -o driver -Wall driver.cc -L../tmp -lstat -lbobcat -s"
# CMD="$GPP -o driver -Wall -I../../tmp driver.cc -L../../tmp/lib -lbobcat -s"
# CMD="$GPP -o driver -Wall -I../ driver.cc -L../tmp -lstat -lbobcat -s"
# CMD="$GPP -o driver -Wall *.cc -lbobcat -s"

echo $CMD
$CMD || exit 1

echo Ready...

