        itemization(
        it() bf(BLOCK_DEVICE) (0060000): the object is a block device;
        it() bf(CHARACTER_DEVICE) (0020000): the object is a character
            device;
        it() bf(DIRECTORY) (0040000): the object is a directory;
        it() bf(FIFO) (0010000): the object is a named pipe (a queue);
        it() bf(REGULAR_FILE) (0100000): the object is a regular file;
        it() bf(SOCKET) (0140000): the object is a socket;
        it() bf(SYMBOLIC_LINK) (0120000): the object is a symbolic link;
        it() bf(ANY): any of the above types.
        )
