#!/bin/bash

tput clear

LIBS=" -lbobcat"
GPP="g++ --std=c++2a"

#   Using the wip ohexstreambuf library and bobcat
# CMD="$GPP -o driver -Wall *.cc -L../tmp -lohexstreambuf -lbobcat -s"


#   Using the wip ohexstreambuf and ofilterstreambuf libraries and bobcat
CMD="$GPP -o driver -I../../tmp -Wall *.cc -L../tmp -lohexstreambuf \
            -L../../ofilterstreambuf/tmp -lofilterstreambuf \
            -L../../eoi/tmp -leoi \
            -lbobcat -s"

echo ${CMD}
${CMD}
