#!/bin/bash

#CMD="g++ `cat ../../c++std` -o driver -Wall -I../../tmp driver.cc -L../../tmp/lib \
#                                                     -lbobcat -s"

# CMD="g++ `cat ../../c++std` -o driver -Wall driver.cc ../*.o -lbobcat -s"
CMD="g++ `cat ../../c++std` -o driver -Wall driver.cc -lbobcat -s"


echo $CMD
$CMD
