#!/bin/sh

# ln -s .. bobcat
# 
# g++ -I. --std=c++2a -O2 -Wall -o driver driver.cc -lssl -lbobcat \
#     -L../../ohexbuf/tmp -L../tmp -lhmacbuf   -lohexbuf
# 

tput clear

LIBS=" -lbobcat -lcrypto"

GPP="g++ --std=c++2a"

#   Using tmp libraries and bobcat
CMD="$GPP -o driver -Wall -I../tmp driver.cc \
    -L../tmp -lofdbuf \
    -L../../eoibuf/tmp -leoibuf \
    -L../../eoi/tmp -leoi \
    ${LIBS} -s"

echo ${CMD}
${CMD}

# rm bobcat
