#!/bin/bash

#   use the std bobcat library:
# g++ --std=c++2a -o driver driver.cc -lbobcat

# use librandbuffer.a and the std bobcat library 
# g++ --std=c++2a -o driver driver.cc -L../tmp -l randbuffer -lbobcat

# use librandbuffer.a and /tmp/libbob.a 
g++ --std=c++2a -o driver driver.cc -L../tmp -l randbuffer -L/tmp -lbob


# g++ --std=c++2a -o driver driver.cc ../*.o -lbobcat
