#!/bin/bash

# ln -s .. bobcat
#g++ -I. --std=c++2a -O2 -Wall -o driver driver.cc -lssl -lbobcat \
#      -L../../ohexstreambuf/tmp -L../tmp -ldigestbuf  -lohexstreambuf
# rm bobcat


tput clear

LIBS=" -lbobcat"
GPP="g++ --std=c++2a"


#CMD="$GPP -o driver -Wall *.cc ${LIBS} -s"

#   Using the library in ../tmp/ and bobcat as /tmp/libbob.a
CMD="$GPP -o driver -Wall *.cc -L../tmp -ldigestbuf -L /tmp -lbob -lcrypto -s"

echo ${CMD}
${CMD}

