#!/bin/bash

# ln -s .. bobcat
# ln -s ../ohexstreambuf/ohexstreambuf bobcat
# 
# g++ -I. --std=c++2a -O2 -Wall -o driver driver.cc -lssl -lbobcat \
#       -L../../ohexstreambuf/tmp -L../tmp -lencryptbuf -lohexstreambuf
# 
# rm bobcat/ohexstreambuf bobcat

# echo g++ --std=c++2a -O2 -Wall -o driver driver.cc -lbobcat 
# g++ --std=c++2a -O2 -Wall -o driver driver.cc -lbobcat 

# echo g++ -I. --std=c++2a -O2 -Wall -o driver driver.cc -L../tmp -lencryptbuf \
#         -lssl -lbobcat
# 
# g++ -I. --std=c++2a -O2 -Wall -o driver driver.cc -L../tmp -lencryptbuf \
#         -lssl -lbobcat

tput clear

LIBS=" -lbobcat -lcrypto"
GPP="g++ --std=c++2a"

#   Using the standard bobcat library
#CMD="$GPP -o driver -Wall driver.cc ${LIBS} -s"

#   Using the library in ../tmp/
#CMD="$GPP -o driver -Wall driver.cc -L../tmp -lencryptbuf ${LIBS} -s"

#   Using the library in ../tmp/ and bobcat as /tmp/libbob.a
#CMD="$GPP -o driver -Wall driver.cc -L../tmp -lencryptbuf -L /tmp -lbob -lcrypto -s"

#   Using the library in ../tmp/, bobcat as /tmp/libbob.a, and librandbuffer
#   in ../../randbuffer/tmp
CMD="$GPP -o driver -Wall driver.cc \
        -L../tmp -lencryptbuf \
        -L../../decryptbuf/tmp -ldecryptbuf \
        -L../../randbuffer/tmp -lrandbuffer -L /tmp -lbob -lcrypto -s"

echo ${CMD}
${CMD}





